Switch to multiple runners per arch
- now uses arm64 native runners for faster compilation

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -18,6 +18,19 @@ concurrency:
   # Don't cancel other runs when creating a tag
   cancel-in-progress: ${{ github.ref_type == 'branch' }}
 
+env:
+  # The *_REPO variables need to be configured as repository variables
+  # Append `/settings/variables/actions` to your repo url
+  # DOCKERHUB_REPO needs to be 'index.docker.io/<user>/<repo>'
+  # Check for Docker hub credentials in secrets
+  HAVE_DOCKERHUB_LOGIN: ${{ vars.DOCKERHUB_REPO != '' && secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}
+  # GHCR_REPO needs to be 'ghcr.io/<user>/<repo>'
+  # Check for Github credentials in secrets
+  HAVE_GHCR_LOGIN: ${{ vars.GHCR_REPO != '' && github.repository_owner != '' && secrets.GITHUB_TOKEN != '' }}
+  # QUAY_REPO needs to be 'quay.io/<user>/<repo>'
+  # Check for Quay.io credentials in secrets
+  HAVE_QUAY_LOGIN: ${{ vars.QUAY_REPO != '' && secrets.QUAY_USERNAME != '' && secrets.QUAY_TOKEN != '' }}
+
 jobs:
   docker-build:
     name: Build Vaultwarden containers
@@ -26,7 +39,7 @@ jobs:
       contents: read
       attestations: write # Needed to generate an artifact attestation for a build
       id-token: write # Needed to mint the OIDC token necessary to request a Sigstore signing certificate
-    runs-on: ubuntu-24.04
+    runs-on: ${{ matrix.arch.os }}
     timeout-minutes: 120
     # Start a local docker registry to extract the compiled binaries to upload as artifacts and attest them
     services:
@@ -38,25 +51,21 @@ jobs:
     env:
       SOURCE_COMMIT: ${{ github.sha }}
       SOURCE_REPOSITORY_URL: "https://github.com/${{ github.repository }}"
-      # The *_REPO variables need to be configured as repository variables
-      # Append `/settings/variables/actions` to your repo url
-      # DOCKERHUB_REPO needs to be 'index.docker.io/<user>/<repo>'
-      # Check for Docker hub credentials in secrets
-      HAVE_DOCKERHUB_LOGIN: ${{ vars.DOCKERHUB_REPO != '' && secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}
-      # GHCR_REPO needs to be 'ghcr.io/<user>/<repo>'
-      # Check for Github credentials in secrets
-      HAVE_GHCR_LOGIN: ${{ vars.GHCR_REPO != '' && github.repository_owner != '' && secrets.GITHUB_TOKEN != '' }}
-      # QUAY_REPO needs to be 'quay.io/<user>/<repo>'
-      # Check for Quay.io credentials in secrets
-      HAVE_QUAY_LOGIN: ${{ vars.QUAY_REPO != '' && secrets.QUAY_USERNAME != '' && secrets.QUAY_TOKEN != '' }}
       PLATFORMS: "['linux/amd64', 'linux/amd64/v3', 'linux/arm64']"
     strategy:
       matrix:
         base_image: ${{ fromJSON(vars.BASE_IMAGE) }}
+        arch:
+          - os: ubuntu-24.04
+            platform: linux/amd64
+            short: amd64
+          - os: ubuntu-24.04-arm
+            platform: linux/arm64
+            short: arm64
 
     outputs:
+      base-tags: ${{ steps.determine-version.outputs.BASE_TAGS }}
       source-version: ${{ steps.determine-version.outputs.SOURCE_VERSION }}
-      platforms: ${{ steps.extract-binaries.outputs.PLTF }}
 
     steps:
       - name: Initialize QEMU binfmt support
@@ -95,12 +104,12 @@ jobs:
         run: |
           # Check which main tag we are going to build determined by ref_type
           if [[ "${REF_TYPE}" == "tag" ]]; then
-            echo "BASE_TAGS=latest,${GITHUB_REF#refs/*/}" | tee -a "${GITHUB_ENV}"
+            echo "BASE_TAGS=latest,${GITHUB_REF#refs/*/}" | tee -a "${GITHUB_OUTPUT}"
           elif [[ "${REF_TYPE}" == "branch" ]]; then
             if [[ "${REF_NAME}" == "main-upstream" ]]; then
-              echo "BASE_TAGS=latest" | tee -a "${GITHUB_ENV}"
+              echo "BASE_TAGS=latest" | tee -a "${GITHUB_OUTPUT}"
             else
-              echo "BASE_TAGS=testing" | tee -a "${GITHUB_ENV}"
+              echo "BASE_TAGS=testing" | tee -a "${GITHUB_OUTPUT}"
             fi
           fi
 
@@ -115,14 +124,16 @@ jobs:
       # End Determine Base Tags
 
       # Login to Docker Hub
-      - name: Login to Docker Hub
+      - &dockerhub-login
+        name: Login to Docker Hub
         uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
         if: ${{ env.HAVE_DOCKERHUB_LOGIN == 'true' }}
 
-      - name: Add registry for DockerHub
+      - &dockerhub-registry
+        name: Add registry for DockerHub
         if: ${{ env.HAVE_DOCKERHUB_LOGIN == 'true' }}
         shell: bash
         env:
@@ -131,7 +142,8 @@ jobs:
           echo "CONTAINER_REGISTRIES=${DOCKERHUB_REPO}" | tee -a "${GITHUB_ENV}"
 
       # Login to GitHub Container Registry
-      - name: Login to GitHub Container Registry
+      - &ghcr-login
+        name: Login to GitHub Container Registry
         uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
         with:
           registry: ghcr.io
@@ -139,7 +151,8 @@ jobs:
           password: ${{ secrets.GITHUB_TOKEN }}
         if: ${{ env.HAVE_GHCR_LOGIN == 'true' }}
 
-      - name: Add registry for ghcr.io
+      - &ghcr-registry
+        name: Add registry for ghcr.io
         if: ${{ env.HAVE_GHCR_LOGIN == 'true' }}
         shell: bash
         env:
@@ -148,7 +161,8 @@ jobs:
           echo "CONTAINER_REGISTRIES=${CONTAINER_REGISTRIES:+${CONTAINER_REGISTRIES},}${GHCR_REPO}" | tee -a "${GITHUB_ENV}"
 
       # Login to Quay.io
-      - name: Login to Quay.io
+      - &quay-login
+        name: Login to Quay.io
         uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
         with:
           registry: quay.io
@@ -156,7 +170,8 @@ jobs:
           password: ${{ secrets.QUAY_TOKEN }}
         if: ${{ env.HAVE_QUAY_LOGIN == 'true' }}
 
-      - name: Add registry for Quay.io
+      - &quay-registry
+        name: Add registry for Quay.io
         if: ${{ env.HAVE_QUAY_LOGIN == 'true' }}
         shell: bash
         env:
@@ -169,12 +184,13 @@ jobs:
         env:
           GHCR_REPO: ${{ vars.GHCR_REPO }}
           BASE_IMAGE: ${{ matrix.base_image }}
+          MATRIX_ARCH_SHORT: ${{ matrix.arch.short }}
         run: |
           #
           # Check if there is a GitHub Container Registry Login and use it for caching
           if [[ -n "${HAVE_GHCR_LOGIN}" ]]; then
-            echo "BAKE_CACHE_FROM=type=registry,ref=${GHCR_REPO}-buildcache:${BASE_IMAGE}" | tee -a "${GITHUB_ENV}"
-            echo "BAKE_CACHE_TO=type=registry,ref=${GHCR_REPO}-buildcache:${BASE_IMAGE},compression=zstd,mode=max" | tee -a "${GITHUB_ENV}"
+            echo "BAKE_CACHE_FROM=type=registry,ref=${GHCR_REPO}-buildcache:${BASE_IMAGE}-${MATRIX_ARCH_SHORT}" | tee -a "${GITHUB_ENV}"
+            echo "BAKE_CACHE_TO=type=registry,ref=${GHCR_REPO}-buildcache:${BASE_IMAGE}-${MATRIX_ARCH_SHORT},compression=zstd,mode=max" | tee -a "${GITHUB_ENV}"
           else
             echo "BAKE_CACHE_FROM="
             echo "BAKE_CACHE_TO="
@@ -186,62 +202,55 @@ jobs:
         run: |
           echo "CONTAINER_REGISTRIES=${CONTAINER_REGISTRIES:+${CONTAINER_REGISTRIES},}localhost:5000/vaultwarden/server" | tee -a "${GITHUB_ENV}"
 
-      - name: Configure bake
-        shell: bash
+      - name: Generate tags
+        id: tags
+        env:
+          CONTAINER_REGISTRIES: "${{ env.CONTAINER_REGISTRIES }}"
         run: |
-          PLATFORMS=$(echo "${{ env.PLATFORMS }}" | tr -d "[' ]")
-          echo "BAKE_PLATFORMS=$PLATFORMS" | tee -a "${GITHUB_ENV}"
+          # Convert comma-separated list to newline-separated set commands
+          TAGS=$(echo "${CONTAINER_REGISTRIES}" | tr ',' '\n' | sed "s|.*|*.tags=&|")
+
+          # Output for use in next step
+          echo "set-value<<EOF" >> $GITHUB_OUTPUT
+          echo "$TAGS" >> $GITHUB_OUTPUT
+          echo "EOF" >> $GITHUB_OUTPUT
 
       - name: Bake ${{ matrix.base_image }} containers
         id: bake_vw
         uses: docker/bake-action@3acf805d94d93a86cce4ca44798a76464a75b88c # v6.9.0
         env:
-          BASE_TAGS: "${{ env.BASE_TAGS }}"
+          BASE_TAGS: "${{ steps.determine-version.outputs.BASE_TAGS }}"
           SOURCE_COMMIT: "${{ env.SOURCE_COMMIT }}"
           SOURCE_VERSION: "${{ steps.determine-version.outputs.SOURCE_VERSION }}"
           SOURCE_REPOSITORY_URL: "${{ env.SOURCE_REPOSITORY_URL }}"
-          CONTAINER_REGISTRIES: "${{ env.CONTAINER_REGISTRIES }}"
         with:
           pull: true
-          push: true
           source: .
           files: docker/docker-bake.hcl
           targets: "${{ matrix.base_image }}-multi"
           set: |
             *.cache-from=${{ env.BAKE_CACHE_FROM }}
             *.cache-to=${{ env.BAKE_CACHE_TO }}
-            *.platform=${{ env.BAKE_PLATFORMS }}
+            *.platform=${{ matrix.arch.platform }}
+            ${{ steps.tags.outputs.set-value }}
+            *.output=type=image,push-by-digest=true,name-canonical=true,push=true,compression=zstd,force-compression=true
 
-      # Attest container images
-      - name: Attest - docker.io - ${{ matrix.base_image }}
-        if: ${{ env.HAVE_DOCKERHUB_LOGIN == 'true' && steps.bake_vw.outputs.metadata != ''}}
-        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
+      - name: Export digest
         env:
-          BASE_IMAGE: ${{ matrix.base_image }}
-        with:
-          subject-name: ${{ vars.DOCKERHUB_REPO }}
-          subject-digest: ${{ fromJSON(steps.bake_vw.outputs.metadata)[format('{0}-multi', env.BASE_IMAGE)]['containerimage.digest'] }}
-          push-to-registry: true
+          EXTRACT_CMD: ${{ fromJSON(steps.bake_vw.outputs.metadata)[format('{0}-multi', matrix.base_image)]['containerimage.digest'] }}
+          RUNNER_TEMP: ${{ runner.temp }}
+        run: |
+          mkdir -p "${RUNNER_TEMP}"/digests
+          digest="${EXTRACT_CMD}"
+          touch "${RUNNER_TEMP}/digests/${digest#sha256:}"
 
-      - name: Attest - ghcr.io - ${{ matrix.base_image }}
-        if: ${{ env.HAVE_GHCR_LOGIN == 'true' && steps.bake_vw.outputs.metadata != ''}}
-        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
-        env:
-          BASE_IMAGE: ${{ matrix.base_image }}
+      - name: Upload digest
+        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
         with:
-          subject-name: ${{ vars.GHCR_REPO }}
-          subject-digest: ${{ fromJSON(steps.bake_vw.outputs.metadata)[format('{0}-multi', env.BASE_IMAGE)]['containerimage.digest'] }}
-          push-to-registry: true
-
-      - name: Attest - quay.io - ${{ matrix.base_image }}
-        if: ${{ env.HAVE_QUAY_LOGIN == 'true' && steps.bake_vw.outputs.metadata != ''}}
-        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
-        env:
-          BASE_IMAGE: ${{ matrix.base_image }}
-        with:
-          subject-name: ${{ vars.QUAY_REPO }}
-          subject-digest: ${{ fromJSON(steps.bake_vw.outputs.metadata)[format('{0}-multi', env.BASE_IMAGE)]['containerimage.digest'] }}
-          push-to-registry: true
+          name: digests-${{ matrix.arch.short }}-${{ matrix.base_image }}
+          path: ${{ runner.temp }}/digests/*
+          if-no-files-found: error
+          retention-days: 1
 
       # Extract the Alpine binaries from the containers
       - name: Extract binaries
@@ -250,6 +259,8 @@ jobs:
         env:
           REF_TYPE: ${{ github.ref_type }}
           BASE_IMAGE: ${{ matrix.base_image }}
+          IMAGE_DIGEST: ${{ fromJSON(steps.bake_vw.outputs.metadata)[format('{0}-multi', matrix.base_image)]['containerimage.digest'] }}
+          MATRIX_ARCH_SHORT: ${{ matrix.arch.short }}
         run: |
           # Check which main tag we are going to build determined by ref_type
           if [[ "${REF_TYPE}" == "tag" ]]; then
@@ -265,69 +276,132 @@ jobs:
             EXTRACT_TAG="${EXTRACT_TAG}-scratch"
           fi
 
-          # After each extraction the image is removed.
-          # This is needed because using different platforms doesn't trigger a new pull/download
+          # Create output directory
+          mkdir -p ./binaries
 
-          PLATFORMS=$(echo "${{ env.PLATFORMS }}" | tr -d "[',linux/]")
-          PLTF=($PLATFORMS)
+          # Create a temporary container and copy binaries
+          CONTAINER_ID=$(docker create localhost:5000/vaultwarden/server:${EXTRACT_TAG}@${IMAGE_DIGEST})
 
-          for DOCKER_ARCH in "${PLTF[@]}"; do
-            docker create --name "${DOCKER_ARCH}" --platform="linux/${DOCKER_ARCH/v//v}" "localhost:5000/vaultwarden/server:${EXTRACT_TAG}"
-            docker cp "${DOCKER_ARCH}":/vaultwarden "vaultwarden-${DOCKER_ARCH}-${BASE_IMAGE}"
-            docker rm --force "${DOCKER_ARCH}"
-            docker rmi --force "localhost:5000/vaultwarden/server:${EXTRACT_TAG}"
-          done
+          # Copy your binary (adjust the path to match your binary location in the container)
+          docker cp $CONTAINER_ID:/vaultwarden ./binaries/vaultwarden-${MATRIX_ARCH_SHORT}
 
-          PLATFORMS=$(echo "${{ env.PLATFORMS }}" | tr -d "linux/")
-          echo "PLTF=$PLATFORMS" | tee -a "$GITHUB_OUTPUT"
+          # Clean up
+          docker rm $CONTAINER_ID
 
-      # Attest the binaries
-      - name: "Attest artifacts ${{ matrix.base_image }}"
+      - name: Attest binaries
         uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
         with:
-          subject-path: vaultwarden-*
+          subject-path: ./binaries/${{ github.event.repository.name }}-${{ matrix.arch.short }}
 
-      - name: Cache between jobs ${{ matrix.base_image }}
-        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
-        env:
-          BASE_IMAGE: ${{ matrix.base_image }}
+      - name: Get short SHA for artefacts
+        id: vars
+        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
+
+      - name: Upload binaries as artifacts
+        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
         with:
-          path: vaultwarden-*-${{ env.BASE_IMAGE }}
-          key: vaultwarden-binaries-${{ steps.determine-version.outputs.SOURCE_VERSION }}-${{ env.BASE_IMAGE }}
+          name: ${{ github.event.repository.name }}-${{ steps.vars.outputs.sha_short }}-linux-${{ matrix.arch.short }}-${{ matrix.base_image }}
+          path: ./binaries/*-${{ matrix.arch.short }}
 
-  upload-artifacts:
-    name: Upload artifacts
-    runs-on: ubuntu-24.04
-    timeout-minutes: 120
+  merge-manifests:
+    name: Merge manifests
+    runs-on: ubuntu-latest
     needs: docker-build
+
+    env:
+      BASE_TAGS: ${{ needs.docker-build.outputs.base-tags }}
+
+    permissions:
+      packages: write # Needed to upload packages and artifacts
+      attestations: write # Needed to generate an artifact attestation for a build
+      id-token: write # Needed to mint the OIDC token necessary to request a Sigstore signing certificate
+
     strategy:
       matrix:
         base_image: ${{ fromJSON(vars.BASE_IMAGE) }}
-        platforms: ${{ fromJSON(needs.docker-build.outputs.platforms) }}
-
-    env:
-      BASE_IMAGE: ${{ matrix.base_image }}
-      MATRIX_PLATFORMS: ${{ matrix.platforms }}
 
     steps:
-      - name: Cache between jobs ${{ matrix.base_image }}
-        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
+      - name: Download digests
+        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
         with:
-          path: vaultwarden-*-${{ env.BASE_IMAGE }}
-          key: vaultwarden-binaries-${{ needs.docker-build.outputs.source-version }}-${{ env.BASE_IMAGE }}
+          path: ${{ runner.temp }}/digests
+          pattern: digests-*-${{ matrix.base_image }}
+          merge-multiple: true
 
-      # Upload artifacts to Github Actions
-      - name: "Upload artifacts ${{ matrix.base_image }}"
-        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
+      - *dockerhub-login
+
+      - *dockerhub-registry
+
+      - *ghcr-login
+
+      - *ghcr-registry
+
+      - *quay-login
+
+      - *quay-registry
+
+      - name: Create manifest list, push it and extract digest SHA
+        working-directory: ${{ runner.temp }}/digests
+        env:
+          BASE_IMAGE: "${{ matrix.base_image }}"
+          BASE_TAGS: "${{ env.BASE_TAGS }}"
+          CONTAINER_REGISTRIES: "${{ env.CONTAINER_REGISTRIES }}"
+        run: |
+          set +e
+          IFS=',' read -ra IMAGES <<< "${CONTAINER_REGISTRIES}"
+          for img in "${IMAGES[@]}"; do
+            echo "Creating manifest for $img:${BASE_TAGS}-${BASE_IMAGE}"
+
+            OUTPUT=$(docker buildx imagetools create \
+              -t "$img:${BASE_TAGS}-${BASE_IMAGE}" \
+              $(printf "$img:${BASE_TAGS}-${BASE_IMAGE}@sha256:%s " *) 2>&1)
+            STATUS=$?
+
+            if [ $STATUS -ne 0 ]; then
+              echo "Manifest creation failed for $img"
+              echo "$OUTPUT"
+            exit $STATUS
+            fi
+
+            echo "Manifest created for $img"
+            echo "$OUTPUT"
+          done
+          set -e
+
+          # Extract digest SHA for subsequent steps
+          GET_DIGEST_SHA="$(echo "$OUTPUT" | grep -oE 'sha256:[a-f0-9]{64}' | head -1)"
+          echo "DIGEST_SHA=${GET_DIGEST_SHA}" | tee -a "${GITHUB_ENV}"
+
+      # Attest container images
+      - name: Attest - docker.io - ${{ matrix.base_image }}
+        if: ${{ env.HAVE_DOCKERHUB_LOGIN == 'true' && env.DIGEST_SHA != ''}}
+        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
         with:
-          name: vaultwarden-${{ needs.docker-build.outputs.source-version }}-linux-${{ env.MATRIX_PLATFORMS }}-${{ env.BASE_IMAGE }}
-          path: vaultwarden-${{ env.MATRIX_PLATFORMS }}-${{ env.BASE_IMAGE }}
+          subject-name: ${{ vars.DOCKERHUB_REPO }}
+          subject-digest: ${{ env.DIGEST_SHA }}
+          push-to-registry: true
+
+      - name: Attest - ghcr.io - ${{ matrix.base_image }}
+        if: ${{ env.HAVE_GHCR_LOGIN == 'true' && env.DIGEST_SHA != ''}}
+        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
+        with:
+          subject-name: ${{ vars.GHCR_REPO }}
+          subject-digest: ${{ env.DIGEST_SHA }}
+          push-to-registry: true
+
+      - name: Attest - quay.io - ${{ matrix.base_image }}
+        if: ${{ env.HAVE_QUAY_LOGIN == 'true' && env.DIGEST_SHA != ''}}
+        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
+        with:
+          subject-name: ${{ vars.QUAY_REPO }}
+          subject-digest: ${{ env.DIGEST_SHA }}
+          push-to-registry: true
 
   deploy:
     name: Deploy
     runs-on: ubuntu-24.04
     timeout-minutes: 120
-    needs: docker-build
+    needs: merge-manifests
 
     env:
       HAVE_WEBHOOK_ENABLED: ${{ secrets.WEBHOOK_URL != '' }}
